/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongratulationsRouteImport } from './routes/congratulations'
import { Route as IndexRouteImport } from './routes/index'

const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongratulationsRoute = CongratulationsRouteImport.update({
  id: '/congratulations',
  path: '/congratulations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/password': typeof PasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/password': typeof PasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/password': typeof PasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/congratulations' | '/dashboard' | '/password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/congratulations' | '/dashboard' | '/password'
  id: '__root__' | '/' | '/congratulations' | '/dashboard' | '/password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongratulationsRoute: typeof CongratulationsRoute
  DashboardRoute: typeof DashboardRoute
  PasswordRoute: typeof PasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congratulations': {
      id: '/congratulations'
      path: '/congratulations'
      fullPath: '/congratulations'
      preLoaderRoute: typeof CongratulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongratulationsRoute: CongratulationsRoute,
  DashboardRoute: DashboardRoute,
  PasswordRoute: PasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
