/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CongratulationsRouteImport } from './routes/congratulations'
import { Route as BusinessInfoRouteImport } from './routes/business-info'
import { Route as BusinessCategoryRouteImport } from './routes/business-category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsIdRouteImport } from './routes/notifications.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CongratulationsRoute = CongratulationsRouteImport.update({
  id: '/congratulations',
  path: '/congratulations',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessInfoRoute = BusinessInfoRouteImport.update({
  id: '/business-info',
  path: '/business-info',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCategoryRoute = BusinessCategoryRouteImport.update({
  id: '/business-category',
  path: '/business-category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIdRoute = NotificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotificationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-category': typeof BusinessCategoryRoute
  '/business-info': typeof BusinessInfoRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/otp': typeof OtpRoute
  '/password': typeof PasswordRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/traffic': typeof TrafficRoute
  '/welcome': typeof WelcomeRoute
  '/notifications/$id': typeof NotificationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-category': typeof BusinessCategoryRoute
  '/business-info': typeof BusinessInfoRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/otp': typeof OtpRoute
  '/password': typeof PasswordRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/traffic': typeof TrafficRoute
  '/welcome': typeof WelcomeRoute
  '/notifications/$id': typeof NotificationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-category': typeof BusinessCategoryRoute
  '/business-info': typeof BusinessInfoRoute
  '/congratulations': typeof CongratulationsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/otp': typeof OtpRoute
  '/password': typeof PasswordRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/traffic': typeof TrafficRoute
  '/welcome': typeof WelcomeRoute
  '/notifications/$id': typeof NotificationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-category'
    | '/business-info'
    | '/congratulations'
    | '/dashboard'
    | '/notifications'
    | '/otp'
    | '/password'
    | '/signup'
    | '/subscription'
    | '/traffic'
    | '/welcome'
    | '/notifications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-category'
    | '/business-info'
    | '/congratulations'
    | '/dashboard'
    | '/notifications'
    | '/otp'
    | '/password'
    | '/signup'
    | '/subscription'
    | '/traffic'
    | '/welcome'
    | '/notifications/$id'
  id:
    | '__root__'
    | '/'
    | '/business-category'
    | '/business-info'
    | '/congratulations'
    | '/dashboard'
    | '/notifications'
    | '/otp'
    | '/password'
    | '/signup'
    | '/subscription'
    | '/traffic'
    | '/welcome'
    | '/notifications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessCategoryRoute: typeof BusinessCategoryRoute
  BusinessInfoRoute: typeof BusinessInfoRoute
  CongratulationsRoute: typeof CongratulationsRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  OtpRoute: typeof OtpRoute
  PasswordRoute: typeof PasswordRoute
  SignupRoute: typeof SignupRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TrafficRoute: typeof TrafficRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congratulations': {
      id: '/congratulations'
      path: '/congratulations'
      fullPath: '/congratulations'
      preLoaderRoute: typeof CongratulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-info': {
      id: '/business-info'
      path: '/business-info'
      fullPath: '/business-info'
      preLoaderRoute: typeof BusinessInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-category': {
      id: '/business-category'
      path: '/business-category'
      fullPath: '/business-category'
      preLoaderRoute: typeof BusinessCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/$id': {
      id: '/notifications/$id'
      path: '/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof NotificationsIdRouteImport
      parentRoute: typeof NotificationsRoute
    }
  }
}

interface NotificationsRouteChildren {
  NotificationsIdRoute: typeof NotificationsIdRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsIdRoute: NotificationsIdRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessCategoryRoute: BusinessCategoryRoute,
  BusinessInfoRoute: BusinessInfoRoute,
  CongratulationsRoute: CongratulationsRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  OtpRoute: OtpRoute,
  PasswordRoute: PasswordRoute,
  SignupRoute: SignupRoute,
  SubscriptionRoute: SubscriptionRoute,
  TrafficRoute: TrafficRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
